name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install gcc-riscv64-unknown-elf -y

    - name: Build kernel.elf
      run: make build-dist && mkdir -p releases

    - name: Upload the kernel
      uses: actions/upload-artifact@v4.3.6
      with:
        name: kernel
        path: ./kernel.elf
        if-no-files-found: error
        overwrite: true
          
